GET http://127.0.0.1:8000/api/students/

###

POST http://127.0.0.1:8000/api/kessons/
Content-Type: application/json

{
  "subjects": 1, 
  "topic":"Past Simple Dimple", 
  "homework": "Past simple", 
  "date": "21.07.2022"
}

###

POST http://127.0.0.1:8000/api/subjects/
Content-Type: application/json

{
  "level": "Продвинутый", 
  "name": "Кря",
  "time": "11:45", 
  "teacher": 2
}

###
POST http://127.0.0.1:8000/api/journals/
Content-Type: application/json

{
 "students": 2,  
 "lessons": 3, 
 "mark": "5"
}

###
POST http://127.0.0.1:8000/api/choices/
Content-Type: application/json

{
"students": 2, 
"year": "2021", 
"semester": "2", 
"sub_first": 1,
"sub_second":2, 
"num_class": "10а"
}

###
DELETE http://127.0.0.1:8000/api/students/8/

###
GET http://127.0.0.1:8000/api/journals/2/
Content-Type: application/json

{
    "students": "Михаил",
    "lessons": "Каташевцев", 
    "mark": "Викторович",  
}

###
POST http://127.0.0.1:8000/api/lessons/2/get-marks/
Content-Type: application/json

{
  "students": 2,
  "lessons": 3, 
  "mark": "5"
}

###
POST http://127.0.0.1:8000/api/schools/
Content-Type: application/json

{
  "title": "Гимназия"
}


###
POST http://127.0.0.1:8000/api/teachers/
Content-Type: application/json

{
 "name": "Михаил",  
 "surname": "Каташевцев", 
 "patr": "Дмитриевич"
}

###
POST http://127.0.0.1:8000/api/teachers/
Content-Type: application/json

{
 "name": "Андрей",  
 "surname": "Дорофеев", 
 "patr": "Сергеевич"
}