# Generated by Django 4.0.5 on 2022-09-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='new_field',
            field=models.TextField(default='', null=True),
        ),
    ]
