# Generated by Django 4.0.5 on 2022-09-19 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0002_teacher_new_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='new_field',
        ),
    ]
