# Generated by Django 4.0.5 on 2022-10-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0005_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='num_class',
        ),
        migrations.AddField(
            model_name='student',
            name='num_class',
            field=models.CharField(max_length=3, null=True, verbose_name='Класс'),
        ),
    ]
