# Generated by Django 4.0.5 on 2022-10-30 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0006_remove_choice_num_class_student_num_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marks.student', verbose_name='ФИО студента'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='sub_first',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_first', to='marks.subject', verbose_name='Предмет № 1'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='sub_second',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_second', to='marks.subject', verbose_name='Предмет № 2'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='lessons',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marks.lesson', verbose_name='Тема урока'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marks.student', verbose_name='ФИО студента'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='homework',
            field=models.CharField(blank=True, max_length=500, verbose_name='Домашнее задание'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subjects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marks.subject', verbose_name='Название предмета'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marks.school', verbose_name='Школа'),
        ),
    ]
